name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  build:
    uses: thiagola92/la-deep-get/.github/workflows/python-package.yml@main
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: pdm publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
