name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/python-package.yml
      - run: pdm publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
