name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - uses: pdm-project/setup-pdm@main
      with:
        python-version: ${{ matrix.python-version }}
    - run: pdm install
    - run: pdm run sort
    - run: pdm run tests
    - run: |
        if [ "$(git status --porcelain)" != "" ]
        then
          git commit -a -m "Workflow fix";
          git push;
        fi